/**
 * Time-addressable Media Store
 *
 * Contact: cloudfit-opensource@rd.bbc.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { UncompressedAudioParameters } from './uncompressed-audio-parameters';
import type { AudioCodecParameters } from './audio-codec-parameters';


/**
 * Describes the parameters of the essence inside this audio Flow
 */
export interface AudioFlowEssenceParameters { 
    /**
     * The fixed number of samples per second.
     */
    sample_rate: number;
    /**
     * The channel count.
     */
    channels: number;
    /**
     * The number of significant bits used to represent the audio sample. The minumum number of bytes then equals `round_up(bit_depth / 8)`. If codec is `audio/x-raw-int` bit_depth must be set. If codec is `audio/x-raw-float` bit_depth must be set to 32 or 64
     */
    bit_depth?: number;
    codec_parameters?: AudioCodecParameters;
    unc_parameters?: UncompressedAudioParameters;
}

