/**
 * Time-addressable Media Store
 *
 * Contact: cloudfit-opensource@rd.bbc.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { ContainerMapping } from './container-mapping';


/**
 * Describes how an object (Source or Flow) is collected into another object of the same type
 */
export interface CollectionItem { 
    /**
     * Source or Flow Identifier of the member of this collection. Sources must only collect Sources, and Flows must only collect Flows. Must already be registered in TAMS
     */
    id: string;
    /**
     * A human-readable role of the element in this collection (e.g. \'R\' to denote a right audio channel in a collection of mono audio Sources)
     */
    role: string;
    container_mapping?: ContainerMapping;
}

