/**
 * Time-addressable Media Store
 *
 * Contact: cloudfit-opensource@rd.bbc.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { ContainerMappingAudioTrack } from './container-mapping-audio-track';
import type { ContainerMappingMxfContainer } from './container-mapping-mxf-container';
import type { ContainerMappingMp2tsContainer } from './container-mapping-mp2ts-container';
import type { ContainerMappingIsobmffContainer } from './container-mapping-isobmff-container';


/**
 * Describes the mapping of the Flow essence from this Flow collection\'s container
 */
export interface ContainerMapping { 
    /**
     * A zero-based and sequential track index in the container. This assumes a reliable ordering of tracks
     */
    track_index?: number;
    /**
     * A zero-based and sequential track index in the container for a particular Flow format. A container with a video and 2 audio tracks would have a format_track_index 0 for the video Flow and format_track_index 0 and 1 for the audio Flows. This assumes a reliable ordering of tracks for each Flow format
     */
    format_track_index?: number;
    audio_track?: ContainerMappingAudioTrack;
    mp2ts_container?: ContainerMappingMp2tsContainer;
    mxf_container?: ContainerMappingMxfContainer;
    isobmff_container?: ContainerMappingIsobmffContainer;
}

