/**
 * Time-addressable Media Store
 *
 * Contact: cloudfit-opensource@rd.bbc.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Identifies the content format for a flow or source using a URN string.
 */
export type Contentformat = 'urn:x-nmos:format:video' | 'urn:x-nmos:format:audio' | 'urn:x-nmos:format:data' | 'urn:x-nmos:format:multi';

export const Contentformat = {
    Video: 'urn:x-nmos:format:video' as Contentformat,
    Audio: 'urn:x-nmos:format:audio' as Contentformat,
    Data: 'urn:x-nmos:format:data' as Contentformat,
    Multi: 'urn:x-nmos:format:multi' as Contentformat
};

