/**
 * Time-addressable Media Store
 *
 * Contact: cloudfit-opensource@rd.bbc.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Mapping for channels in audio tracks to the Flow channels
 */
export interface ContainerMappingAudioTrack { 
    /**
     * Array of (zero-based) container channel numbers in Flow order
     */
    channel_numbers?: Array<number>;
    /**
     * Inclusive range of (zero-based) container channel numbers
     */
    channel_range?: string;
}

