/**
 * Time-addressable Media Store
 *
 * Contact: cloudfit-opensource@rd.bbc.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Mapping to Material Exchange Format containers, SMPTE ST 377-1
 */
export interface ContainerMappingMxfContainer { 
    /**
     * The package UID. Either a SMPTE UMID URN or UUID URN
     */
    package_uid?: string;
    /**
     * The track ID in the package
     */
    track_id?: number;
}

