/**
 * Time-addressable Media Store
 *
 * Contact: cloudfit-opensource@rd.bbc.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { DeletionRequestError } from './deletion-request-error';


/**
 * Describes an ongoing deletion request
 */
export interface DeletionRequest { 
    /**
     * Deletion Request ID
     */
    id: string;
    /**
     * ID of the flow to which the deletion request relates
     */
    flow_id: string;
    /**
     * The timerange of FlowSegments to be deleted in this request, as described by the [TimeRange](../schemas/timerange#top) type
     */
    timerange_to_delete: string;
    /**
     * The timerange of FlowSegments not yet deleted by this request, as described by the [TimeRange](../schemas/timerange#top) type
     */
    timerange_remaining?: string;
    /**
     * Whether the Flow should be deleted once the timerange has been
     */
    delete_flow: boolean;
    /**
     * Date/Time when this deletion request was created
     */
    created?: string;
    /**
     * A string identifier for the entity that created the deletion request. Implementations SHOULD set suitable default values for `created_by` based on the principal accessing the system, and MAY permit clients to edit the value, subject to suitable permissions-based limitations.
     */
    created_by?: string;
    /**
     * Date/Time when this deletion request was updated
     */
    updated?: string;
    /**
     * Date/Time when this deletion request will be deleted
     */
    expiry?: string;
    /**
     * Status of the delete request
     */
    status: DeletionRequest.StatusEnum;
    error?: DeletionRequestError;
}
export namespace DeletionRequest {
    export type StatusEnum = 'created' | 'started' | 'done' | 'error';
    export const StatusEnum = {
        Created: 'created' as StatusEnum,
        Started: 'started' as StatusEnum,
        Done: 'done' as StatusEnum,
        Error: 'error' as StatusEnum
    };
}


