/**
 * Time-addressable Media Store
 *
 * Contact: cloudfit-opensource@rd.bbc.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Provides more information for the error status.
 */
export interface DeletionRequestError { 
    /**
     * The error type name.
     */
    type: string;
    /**
     * Summary description of the error and causes.
     */
    summary: string;
    /**
     * Stack trace leading to error (as a list of strings)
     */
    traceback?: Array<string>;
    /**
     * Time at which the error ocurred, to aid in log correlation
     */
    time: string;
}

