/**
 * Time-addressable Media Store
 *
 * Contact: cloudfit-opensource@rd.bbc.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Describes an event stream mechanism available in this implementation of TAMS
 */
export interface EventStreamMechanism { 
    /**
     * Name of this type of event stream mechanism. Must be unique. Any name defined in this specification is reserved
     */
    name: string;
    /**
     * Location (e.g. a URL) at which documentation for this event stream mechanism may be found
     */
    docs?: string;
    /**
     * Configuration options required to make use of this mechanism
     */
    config?: object;
}

