/**
 * Time-addressable Media Store
 *
 * Contact: cloudfit-opensource@rd.bbc.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { FlowSegmentGetUrlsInner } from './flow-segment-get-urls-inner';


/**
 * Provides the location and metadata of the media files corresponding to timerange segments of a Flow.
 */
export interface FlowSegment1 { 
    /**
     * The object store identifier for the media object.
     */
    object_id: string;
    /**
     * The timestamp offset between the sample timestamps stored in the media file and the corresponding timestamp in the segment, ie. ts_offset = segment ts - media object ts. Assumed to be 0:0 if not set. Format as described by the [Timestamp](../schemas/timestamp#top) type, but cannot be negative
     */
    ts_offset?: string;
    /**
     * The timerange for the samples contained in the segment. The timerange start is always inclusive. If samples have a duration then the timerange end is exclusive and covers at least the duration of the last sample. The exclusive timerange end will typically be set to the timestamp of the next sample. If the samples don\'t have a duration then the timerange end is inclusive. Format is described by the [TimeRange](../schemas/timerange#top) type. Note that where temporal re-ordering is used, the timerange and samples refers to the presentation timeline.
     */
    timerange: string;
    /**
     * The difference between the exclusive end of the `timerange` and the last sample timestamp. Format as described by the [Timestamp](../schemas/timestamp#top) type, but cannot be negative
     */
    last_duration?: string;
    /**
     * The start of the segment represented as a count of samples from the start of the object. Note that a sample is a video frame or audio sample. A (coded) audio frame has multiple audio samples. Assumed to be 0 if not set.
     */
    sample_offset?: number;
    /**
     * The count of samples in the segment (which may be fewer than in the object). The count could be less than expected given the segment duration and rate if there are gaps. If not set, every sample from sample_offset onwards is used. Note that a sample is a video frame or audio sample. A (coded) audio frame has multiple audio samples
     */
    sample_count?: number;
    /**
     * A list of URLs to which a GET request can be made to directly retrieve the contents of the segment. This is required by the `http_object_store` media store type, which is the only one currently described. Clients may choose any URL in the list and treat them as identical, however servers may sort the list such that the preferred URL is first.
     */
    get_urls?: Array<FlowSegmentGetUrlsInner>;
    /**
     * The number of key frames in the segment. This should be set greater than zero when the segment contains key frames that serve as a stream access point
     */
    key_frame_count?: number;
}

