/**
 * Time-addressable Media Store
 *
 * Contact: cloudfit-opensource@rd.bbc.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Post data for the flow storage endpoint
 */
export interface FlowStoragePost { 
    /**
     * Limit the number of storage segments in each response page. Implementations may specify their own default and maximum for the limit
     */
    limit?: number;
}

