/**
 * Time-addressable Media Store
 *
 * Contact: cloudfit-opensource@rd.bbc.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FlowSegmentGetUrlsInner { 
    /**
     * Label identifying this URL. If the \'label\' is not set then this URL can\'t be filtered for using the \'accept_get_urls\' API query parameter.
     */
    label?: string;
    /**
     * A URL to which a GET request can be made to directly retrieve the contents of the segment. Clients should include credentials if the provide URL is on the same origin as the API endpoint
     */
    url: string;
}

