/**
 * Time-addressable Media Store
 *
 * Contact: cloudfit-opensource@rd.bbc.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Gives information on a particular http request a client should perform
 */
export interface HTTPRequest { 
    /**
     * The URL to make the request to
     */
    url: string;
    /**
     * The text of the body which needs to be included in the request
     */
    body?: string;
    /**
     * The content type which must be used
     */
    'content-type'?: string;
    /**
     * Additional headers that should be included
     */
    headers?: { [key: string]: string; };
}

