/**
 * Time-addressable Media Store
 *
 * Contact: cloudfit-opensource@rd.bbc.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { FlowCoreSegmentDuration } from "./flow-core-segment-duration";
import type { ContainerMapping1 } from "./container-mapping1";
import type { CollectionItem } from "./collection-item";
import type { ImageFlowEssenceParameters } from "./image-flow-essence-parameters";

/**
 * Describes a image Flow
 */
export interface ImageFlow {
  /**
   * Flow identifier
   */
  id: string;
  /**
   * Source identifier
   */
  source_id: string;
  /**
   * Freeform string label for the flow
   */
  label?: string;
  /**
   * Freeform text describing the flow
   */
  description?: string;
  /**
   * A string identifier for the entity that created the flow. Implementations SHOULD set suitable default values for `created_by` based on the principal accessing the system, and MAY permit clients to edit the value, subject to suitable permissions-based limitations.
   */
  created_by?: string;
  /**
   * A string identifier for the entity that updated the flow metadata most recently. Implementations SHOULD set suitable default values for `updated_by` based on the principal accessing the system, and MAY permit clients to edit the value, subject to suitable permissions-based limitations.
   */
  updated_by?: string;
  /**
   * Key value is a freeform string.
   */
  tags?: { [key: string]: string | string[] };
  /**
   * A change to the flow metadata, not including metadata_version, last_update or segments, results in a new version. If the metadata_version for flow instances is identical then the metadata is identical.
   */
  metadata_version?: string;
  /**
   * An indication of how many lossy encodings the flow content has been through. A flow with a higher generation may contain less of the original information than a flow with a lower generation.
   */
  generation?: number;
  /**
   * The date-time the flow was created in a given context, e.g. in the store. Implementations SHOULD ignore this if given in a PUT request, and instead manage it internally
   */
  created?: string;
  /**
   * The date-time the flow metadata was updated in a given context, e.g. in the store. Implementations SHOULD ignore this if given in a PUT request, and instead manage it internally
   */
  metadata_updated?: string;
  /**
   * The date-time the flow segments were updated in a given context, e.g. in the store. Implementations SHOULD ignore this if given in a PUT request, and instead manage it internally
   */
  segments_updated?: string;
  /**
   * State of the flow in the store, e.g. `ingesting` while it is still being written to
   */
  status?: string;
  /**
   * If set to \'true\', implementations SHOULD reject client requests to update Flow metadata (other than the read_only property), Flow Segments and media objects
   */
  read_only?: boolean;
  /**
   * A MIME type identification of the (lossy or lossless) coding used for the flow content.
   */
  codec?: string;
  /**
   * The container MIME type for flow segments.
   */
  container?: string;
  /**
   * The average bit rate of the flow segments in 1000 bits/second. A precise definition can be found in the [Setting Flow Bit Rate Properties](https://github.com/bbc/tams/blob/main/docs/appnotes/0013-setting-flow-bit-rate-properties.md) AppNote.
   */
  avg_bit_rate?: number;
  /**
   * The maximum bit rate of the flow segments in 1000 bits/second. A precise definition can be found in the [Setting Flow Bit Rate Properties](https://github.com/bbc/tams/blob/main/docs/appnotes/0013-setting-flow-bit-rate-properties.md) AppNote.
   */
  max_bit_rate?: number;
  segment_duration?: FlowCoreSegmentDuration;
  /**
   * The timerange of samples available in the flow, as described by the [TimeRange](../schemas/timerange#top) type
   */
  timerange?: string;
  /**
   * List of Flows that are collected together by this Flow.
   */
  flow_collection?: Array<CollectionItem>;
  /**
   * Flows that reference this Flow to include it in a collection. This attribute is intended to be read-only. Implementations SHOULD ignore this if given in a PUT request, and instead manage it internally
   */
  collected_by?: Array<string>;
  container_mapping?: ContainerMapping1;
  /**
   * The primary content type URN for the flow.
   */
  format: ImageFlow.FormatEnum;
  essence_parameters: ImageFlowEssenceParameters;
}
export namespace ImageFlow {
  export type FormatEnum = "urn:x-tam:format:image";
  export const FormatEnum = {
    UrnxNmosformatdata: "urn:x-tam:format:image" as FormatEnum,
  };
}
