/**
 * Time-addressable Media Store
 *
 * Contact: cloudfit-opensource@rd.bbc.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Describes the parameters of the essence inside this image Flow
 */
export interface ImageFlowEssenceParameters {
  /**
   * Parameters describing the essence of image Flow
   */
  frame_width: number;
  frame_height: number;
}
