/**
 * Time-addressable Media Store
 *
 * Contact: cloudfit-opensource@rd.bbc.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { MediaBucketObjectStorePreInner } from './media-bucket-object-store-pre-inner';
import type { MediaBucketObjectStoreMediaObjectsInner } from './media-bucket-object-store-media-objects-inner';


/**
 * Gives information on storage for media objects. This schema is for the `http_object_store` media store type which provides URLs for storing media objects in bucket, and is the only store type currently implemented.
 */
export interface MediaBucketObjectStore { 
  [key: string]: any | any;


    /**
     * Actions that need to be taken before the media object can be written
     */
    pre?: Array<MediaBucketObjectStorePreInner>;
    /**
     * List of information for identifying and uploading media objects
     */
    media_objects?: Array<MediaBucketObjectStoreMediaObjectsInner>;
}

