/**
 * Time-addressable Media Store
 *
 * Contact: cloudfit-opensource@rd.bbc.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { HTTPRequest } from './http-request';


/**
 * An action
 */
export interface MediaBucketObjectStorePreInner { 
    action: MediaBucketObjectStorePreInner.ActionEnum;
    /**
     * The name of the bucket that needs to be created
     */
    bucket_id?: string;
    put_url?: HTTPRequest;
    put_cors_url?: HTTPRequest;
}
export namespace MediaBucketObjectStorePreInner {
    export type ActionEnum = 'create_bucket';
    export const ActionEnum = {
        CreateBucket: 'create_bucket' as ActionEnum
    };
}


