/**
 * Time-addressable Media Store
 *
 * Contact: cloudfit-opensource@rd.bbc.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { HTTPRequest } from './http-request';


/**
 * Information for a media object
 */
export interface MediaBucketObjectStoreMediaObjectsInner { 
    /**
     * The object store identifier for the media object.
     */
    object_id: string;
    put_url: HTTPRequest;
    put_cors_url?: HTTPRequest;
}

