/**
 * Time-addressable Media Store
 *
 * Contact: cloudfit-opensource@rd.bbc.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Register to receive updates via webhook
 */
export interface RegisterWebhook { 
    /**
     * The URL to which the API should make HTTP POST requests with event data
     */
    url: string;
    /**
     * The HTTP header name that is added to the event POST
     */
    api_key_name?: string;
    /**
     * The value that the HTTP header \'api_key_name\' will be set to
     */
    api_key_value?: string;
    /**
     * List of event types to receive
     */
    events: Array<string>;
    /**
     * Limit Flow and Flow Segment events to Flows in the given list of Flow IDs
     */
    flow_ids?: Array<string>;
    /**
     * Limit Flow, Flow Segment and Source events to Sources in the given list of Source IDs
     */
    source_ids?: Array<string>;
    /**
     * Limit Flow and Flow Segment events to those with Flow that is collected by a Flow Collection in the given list of Flow Collection IDs
     */
    flow_collected_by_ids?: Array<string>;
    /**
     * Limit Flow, Flow Segment and Source events to those with Source that is collected by a Source Collection in the given list of Source Collection IDs
     */
    source_collected_by_ids?: Array<string>;
    /**
     * List of labels of URLs to include in the `get_urls` property in `flows/segments_added` events. This option is the same as the `accept_get_urls` query parameter for the /flows/{flowId}/segments API endpoint, except that the labels are represented using a JSON array rather than a (comma separated list) string.
     */
    accept_get_urls?: Array<string>;
}

