/**
 * Time-addressable Media Store
 *
 * Contact: cloudfit-opensource@rd.bbc.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { ServiceMediaStore } from './service-media-store';
import type { EventStreamMechanism } from './event-stream-mechanism';


/**
 * Provides information about the store service
 */
export interface Service { 
    /**
     * The service instance name
     */
    name?: string;
    /**
     * The service instance description
     */
    description?: string;
    /**
     * The type identifier for the service. The value must start with \'urn:x-tams:service\'
     */
    type: string;
    /**
     * The version of the TAMS API specification this deployment implements
     */
    api_version: string;
    /**
     * The version of software providing this service. Note: Different implementations and software houses may use different conventions for their version identification. As such, this field is intentionally permissive and intended to be informative only. Implementations should avoid using this field to determine compatibility.
     */
    service_version?: string;
    media_store: ServiceMediaStore;
    /**
     * List the types of event stream that this implementation supports
     */
    event_stream_mechanisms?: Array<EventStreamMechanism>;
}

