/**
 * Time-addressable Media Store
 *
 * Contact: cloudfit-opensource@rd.bbc.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { CollectionItem } from "./collection-item";

/**
 * Describes a Source: an abstract representation of a piece of media as defined in <https://specs.amwa.tv/ms-04/releases/v1.0.0/docs/2.2._Explanation_-_Source.html>  Sources may be elemental (and represented directly by a Flow), or may represent a collection of other Sources, e.g. a Source collecting video and audio together.
 */
export interface Source {
  /**
   * Source identifier
   */
  id: string;
  /**
   * The primary content type URN for the Source.
   */
  format: Source.FormatEnum;
  /**
   * Freeform string label for the Source
   */
  label?: string;
  /**
   * Freeform text describing the Source
   */
  description?: string;
  /**
   * A string identifier for the entity that created the Source. Implementations SHOULD set suitable default values for `created_by` based on the principal accessing the system, and MAY permit clients to edit the value, subject to suitable permissions-based limitations.
   */
  created_by?: string;
  /**
   * A string identifier for the entity that updated the Source metadata most recently. Implementations SHOULD set suitable default values for `updated_by` based on the principal accessing the system, and MAY permit clients to edit the value, subject to suitable permissions-based limitations.
   */
  updated_by?: string;
  /**
   * The date-time the Source was created in a given context, e.g. in the store. Implementations SHOULD ignore this if given in a PUT request, and instead manage it internally
   */
  created?: string;
  /**
   * The date-time the Source metadata was last updated in a given context, e.g. in the store. Implementations SHOULD ignore this if given in a PUT request, and instead manage it internally
   */
  updated?: string;
  /**
   * Key value is a freeform string.
   */
  tags?: { [key: string]: string | string[] };
  /**
   * List of Sources that are collected together by this Source. This attribute is intended to be read-only. Implementations SHOULD ignore this if given in a PUT request, and instead manage it internally. Source collections can be inferred from Flow collection definitions.
   */
  source_collection?: Array<CollectionItem>;
  /**
   * Sources that reference this Source to include it in a collection. This attribute is intended to be read-only. Implementations SHOULD ignore this if given in a PUT request, and instead manage it internally. Source collections can be inferred from Flow collection definitions.
   */
  collected_by?: Array<string>;
}
export namespace Source {
  export type FormatEnum =
    | "urn:x-nmos:format:video"
    | "urn:x-nmos:format:audio"
    | "urn:x-nmos:format:data"
    | "urn:x-nmos:format:multi";
  export const FormatEnum = {
    Video: "urn:x-nmos:format:video" as FormatEnum,
    Audio: "urn:x-nmos:format:audio" as FormatEnum,
    Data: "urn:x-nmos:format:data" as FormatEnum,
    Multi: "urn:x-nmos:format:multi" as FormatEnum,
  };
}
