/**
 * Time-addressable Media Store
 *
 * Contact: cloudfit-opensource@rd.bbc.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UncompressedAudioParameters { 
    /**
     * The uncompressed audio multi-channel representation type. If codec is `audio/x-raw-int` or `audio/x-raw-float`, unc_type must be set.
     */
    unc_type: UncompressedAudioParameters.UncTypeEnum;
}
export namespace UncompressedAudioParameters {
    export type UncTypeEnum = 'interleaved' | 'planar' | 'pairs';
    export const UncTypeEnum = {
        Interleaved: 'interleaved' as UncTypeEnum,
        Planar: 'planar' as UncTypeEnum,
        Pairs: 'pairs' as UncTypeEnum
    };
}


