/**
 * Time-addressable Media Store
 *
 * Contact: cloudfit-opensource@rd.bbc.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UncompressedVideoParameters { 
    /**
     * Uncompressed picture packing type. If codec is `video/raw`, unc_type must be set.
     */
    unc_type: UncompressedVideoParameters.UncTypeEnum;
}
export namespace UncompressedVideoParameters {
    export type UncTypeEnum = 'planar' | 'YUYV' | 'UYVY' | 'AYUV' | 'v210' | 'v216' | 'RGB' | 'RGBx' | 'xRGB' | 'BGRx' | 'xBGR' | 'RGBA' | 'ARGB' | 'BGRA' | 'ABGR' | 'alpha';
    export const UncTypeEnum = {
        Planar: 'planar' as UncTypeEnum,
        Yuyv: 'YUYV' as UncTypeEnum,
        Uyvy: 'UYVY' as UncTypeEnum,
        Ayuv: 'AYUV' as UncTypeEnum,
        V210: 'v210' as UncTypeEnum,
        V216: 'v216' as UncTypeEnum,
        Rgb: 'RGB' as UncTypeEnum,
        Rgbx: 'RGBx' as UncTypeEnum,
        XRgb: 'xRGB' as UncTypeEnum,
        Bgrx: 'BGRx' as UncTypeEnum,
        XBgr: 'xBGR' as UncTypeEnum,
        Rgba: 'RGBA' as UncTypeEnum,
        Argb: 'ARGB' as UncTypeEnum,
        Bgra: 'BGRA' as UncTypeEnum,
        Abgr: 'ABGR' as UncTypeEnum,
        Alpha: 'alpha' as UncTypeEnum
    };
}


