/**
 * Time-addressable Media Store
 *
 * Contact: cloudfit-opensource@rd.bbc.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Post update to the service info
 */
export interface UpdateServiceInfo { 
    /**
     * The service instance name
     */
    name?: string;
    /**
     * The service instance description
     */
    description?: string;
}

