/**
 * Time-addressable Media Store
 *
 * Contact: cloudfit-opensource@rd.bbc.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The fixed number of frames per second. If this parameter is unset, the frame_rate is either unknown or variable.
 */
export interface VideoFlowEssenceParametersFrameRate { 
    /**
     * numerator
     */
    numerator: number;
    /**
     * denominator
     */
    denominator?: number;
}

