/**
 * Time-addressable Media Store
 *
 * Contact: cloudfit-opensource@rd.bbc.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The display aspect ratio. i.e. display_width / display_height
 */
export interface VideoFlowEssenceParametersAspectRatio { 
    /**
     * numerator
     */
    numerator: number;
    /**
     * denominator
     */
    denominator: number;
}

